variables:
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: '$CI_PROJECT_DIR/src'
  OUTPUT_PATH: '$CI_PROJECT_DIR/dist/hv-z'

install_dependencies:
  image: node:15-alpine
  stage: .pre
  script:
    - npm install
  only:
    - main
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

build_image:
  image: node:14-alpine
  stage: build
  script:
    - npm link @angular/cli@15.2.1
    - npm run build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

push-gitlab-registry:
  image: docker:latest
  stage: build
  only:
    - main
  script:
    - docker build -t registry.gitlab.com/sondreeftedal/hv-z .
    - docker login -u sondreeftedal -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/sondreeftedal/hv-z
  services:
    - docker:dind
deploy:
  stage: deploy
  image: registry.gitlab.com/SondreEftedal/hv-z
  script:
    - echo "App deployed successfully."